#!/bin/zsh
DATASET="${DATASET:-snowboards}"
#
# preprocess_csv.sh
#
# Runs preprocessing on the raw comparison CSV to produce the processed CSV.
# Paths are relative to the dataset folder data_processing/${DATASET}/.
#
# Prerequisites:
#   - ${DATASET}/product_comparison.csv must already exist (from copy_grounding_data_from_fact_collation.sh)
#   - ${DATASET}/product_criteria_spec.json must have been generated by an LLM using:
#       - criteria_spec_schema.md (defines the JSON schema)
#       - create_new_criteria_spec_prompt.md (generation instructions)
#       - ${DATASET}/product_comparison.csv (raw data)
#       - ${DATASET}/comparison_columns.json (column metadata)
#
# Output:
#   - ${DATASET}/product_comparison_processed.csv
#
# NOTE: the DATASET env var above is informational for these comments; the
# authoritative dataset switch is the DATASET constant in preprocessing.py.

set -euo pipefail

SCRIPT_DIR="${0:a:h}"
PROJECT_ROOT="${SCRIPT_DIR}/.."

echo "Running preprocessing (raw CSV → processed CSV)..."
PYTHONPATH="${PROJECT_ROOT}${PYTHONPATH:+:$PYTHONPATH}" uv run python "${SCRIPT_DIR}/preprocessing.py"
echo "  → ${SCRIPT_DIR}/${DATASET}/product_comparison_processed.csv"
echo ""
echo "Done."
