#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""CLI runner for the Eudoxa decision model for manual checking.

Replicates the exact code path that agent.py → tools.run_model → broker.run_decision_model
follows, including preprocessing and simulation config merging.

Usage:
    python -m server.agent.cli_run [OPTIONS]

    # Or directly:
    python server/agent/cli_run.py [OPTIONS]

Options:
    --csv PATH              Path to comparison CSV (default: data_processing/<DATASET>/product_comparison_processed.csv)
    --spec PATH             Path to criteria spec JSON (default: data_processing/<DATASET>/product_criteria_spec.json)
    --sim-config PATH       Path to simulation config JSON (default: data_processing/<DATASET>/simulation_config.json)
    --n-samples INT         Number of MC samples (default: 5000, matching agent tool default)
    --top-n INT             Number of top products to return (default: 5)
    --preferences JSON      JSON string of preference transforms (default: none)
    --output PATH           Write result JSON to file (default: print to stdout)
    --quiet                 Suppress progress messages (only output JSON)
"""

from __future__ import annotations

# Dataset folder (under data_processing/) this CLI operates on.
DATASET = "snowboards"

import argparse
import json
import sys
import time
from pathlib import Path

# Ensure project root is on sys.path so top-level packages import correctly.
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from decision_model import runner


def _default_path(relative: str) -> str:
    """Resolve a path relative to the project root."""
    return str(PROJECT_ROOT / relative)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Run the Eudoxa decision model from the command line.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--csv",
        default=_default_path(f"data_processing/{DATASET}/product_comparison_processed.csv"),
        help="Path to pre-processed comparison CSV (generated by data_processing/preprocessing.py)",
    )
    parser.add_argument(
        "--spec",
        default=_default_path(f"data_processing/{DATASET}/product_criteria_spec.json"),
        help="Path to criteria spec JSON",
    )
    parser.add_argument(
        "--sim-config",
        default=_default_path(f"data_processing/{DATASET}/simulation_config.json"),
        help="Path to simulation config JSON (merged into spec's monte_carlo block)",
    )
    parser.add_argument(
        "--n-samples",
        type=int,
        default=5000,
        help="Number of MC simulation samples (agent tool default: 5000)",
    )
    parser.add_argument(
        "--top-n",
        type=int,
        default=5,
        help="Number of top products to include in results",
    )
    parser.add_argument(
        "--preferences",
        type=str,
        default="[]",
        help='JSON array of preference transforms, e.g. \'[{"type":"set_weight","target_criterion":"carving_rating","parameters":{"weight":0.20}}]\'',
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Write result JSON to this file (default: stdout)",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress progress messages",
    )

    args = parser.parse_args()

    def log(msg: str) -> None:
        if not args.quiet:
            print(f"[eudoxa-cli] {msg}", file=sys.stderr)

    # ── 1-3. Load inputs (spec + sim-config merge + processed CSV) ───
    log(f"Loading criteria spec: {args.spec}")
    log(f"Merging simulation config (if present): {args.sim_config}")
    log(f"Loading pre-processed CSV: {args.csv}")
    try:
        processed_df, criteria_spec = runner.load_inputs(
            csv=args.csv, spec=args.spec, sim_config=args.sim_config
        )
    except FileNotFoundError as e:
        print(str(e), file=sys.stderr)
        sys.exit(1)
    log(f"  → {len(processed_df)} alternatives, {len(processed_df.columns)} columns")

    # ── 4. Parse preference transforms ───────────────────────────────
    try:
        preferences = json.loads(args.preferences)
    except json.JSONDecodeError as e:
        print(f"Invalid --preferences JSON: {e}", file=sys.stderr)
        sys.exit(1)

    if not isinstance(preferences, list):
        print("--preferences must be a JSON array", file=sys.stderr)
        sys.exit(1)

    if preferences:
        log(f"Applying {len(preferences)} preference transform(s)...")
    else:
        log("No preferences (baseline run)")

    # ── 5-7. Run the decision pipeline ───────────────────────────────
    # --n-samples overrides the spec/sim-config value (agent tool default 5000).
    log("Running Monte Carlo simulation...")
    t0 = time.time()
    try:
        result = runner.run_decision(
            processed_df,
            criteria_spec,
            preferences=preferences,
            mc_overrides={"n_samples": args.n_samples},
            top_n=args.top_n,
            include_diagnostics=False,
        )
    except ValueError as e:
        print(f"Decision run failed: {e}", file=sys.stderr)
        sys.exit(1)

    mc_params = result["mc_params"]
    log(
        f"  n_samples={mc_params['n_samples']}, "
        f"perturbation={mc_params['weight_perturbation']}, "
        f"vikor_v={mc_params['vikor_v']}, "
        f"seed={mc_params['random_seed']}, dormant_budget={mc_params['dormant_budget']}"
    )
    log(f"  → Simulation complete ({time.time() - t0:.2f}s)")

    output = result["decision"]

    # ── 8. Output ────────────────────────────────────────────────────
    json_str = json.dumps(output, indent=2, default=str)

    if args.output:
        Path(args.output).write_text(json_str, encoding="utf-8")
        log(f"Result written to: {args.output}")
    else:
        print(json_str)

    # Print a brief summary to stderr
    rec = output.get("recommended", {})
    conf = output.get("confidence", {})
    log(f"\n{'=' * 60}")
    log(f"  Recommended: {rec.get('title', '?')}")
    log(f"  Confidence:  {conf.get('level', '?')} ({conf.get('score', 0):.1%})")
    log(f"  Clear winner: {output.get('has_clear_winner', '?')}")
    log(f"{'=' * 60}")


if __name__ == "__main__":
    main()
